server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
  port: 9090
  servlet:
    context-path: /emos-workflow

spring:
  servlet:
    multipart:
      # 允许上传文件
      enabled: true
      # 每个文件最大不能超过20M
      max-file-size: 20MB
      # HTTP请求不能超过20MB
      max-request-size: 20MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: abc123456
      initial-size: 2
      max-active: 4
      min-idle: 4
      max-wait: 60000
      test-while-idle: false
      test-on-borrow: true
      test-on-return: false
  redis:
    database: 0
    host: localhost
    port: 6379
    password: abc123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  activiti:
    database-schema-update: true
    historyLevel: audit
    db-history-used: true
  quartz:
    job-store-type: jdbc
  mail:
    default-encoding: UTF-8
    host: SMTP服务器地址
    port: 465
    username: 邮箱用户名
    password: 邮箱密码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.emos.workflow.db.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.emos.workflow.db.dao: error
  pattern:
    console: "%d{yyyy/MM/dd HH:mm:ss}  %-5level  %msg%n"
